/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kaan.schoolmanagementmaven.admin;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import com.kaan.schoolmanagementmaven.exception.InvalidBalanceException;
import com.kaan.schoolmanagementmaven.exception.InvalidDebtException;
import com.kaan.schoolmanagementmaven.exception.InvalidLessonCreditException;
import com.kaan.schoolmanagementmaven.exception.InvalidPassLengthException;
import com.kaan.schoolmanagementmaven.exception.InvalidPhoneCountryCodeException;
import com.kaan.schoolmanagementmaven.exception.InvalidPhoneNumberLengthException;
import com.kaan.schoolmanagementmaven.exception.InvalidUsernameLengthException;
import com.kaan.schoolmanagementmaven.exception.NotUniqueNameAndLastnameException;
import com.kaan.schoolmanagementmaven.exception.NotUniquePhoneNumberException;
import com.kaan.schoolmanagementmaven.exception.NotUniqueUsernameAndPassException;

/**
 *
 * @author kaan
 * 
 */
public class AdminStudentChangingPanel extends javax.swing.JFrame {

    private ResultSet studentInfo;
    private IAdminSettingManager settingManager;
    private String nameDb;
    private String lastNameDb;
    private String userNameDb;
    private String passDb;
    private String phoneNumberDb;
    private int balanceDb;
    private int debtDb;
    private int lessonCreditDb;

    /**
     * Creates new form AdminStudentChangingPanel
     * @param main
     * @param studentResultSet
     * @param userName
     * @param password
     * @param lessonCreditColumn
     * @throws java.sql.SQLException
     */
    public AdminStudentChangingPanel(AdminPersonChangingMainPanel main, ResultSet studentResultSet, String userName, String password, String lessonCreditColumn) throws SQLException {
        initComponents();
        studentInfo = studentResultSet;
        nameDb = studentInfo.getString("name");
        name.setText(nameDb);
        lastNameDb = studentInfo.getString("last_name");
        lastName.setText(lastNameDb);
        userNameDb = userName;
        this.userName.setText(userNameDb);
        passDb = password;
        pass.setText(passDb);
        balanceDb = studentInfo.getInt("balance");
        balance.setText(Integer.toString(balanceDb));
        debtDb = studentInfo.getInt("debt");
        debt.setText(Integer.toString(debtDb));
        lessonCreditDb = studentInfo.getInt(lessonCreditColumn);
        lessonCredit.setText(Integer.toString(lessonCreditDb));
        phoneNumberDb = studentInfo.getString("phone_number");
        phoneNumberTf.setText(phoneNumberDb);
        settingManager = AdminSettingManager.getInstance();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                main.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        debt = new javax.swing.JTextField();
        lessonCredit = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        phoneNumberTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Lastname");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Balance");

        jLabel6.setText("Debt");

        jLabel7.setText("Lesson Credit");

        debt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtActionPerformed(evt);
            }
        });

        lessonCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonCreditActionPerformed(evt);
            }
        });

        changeButton.setText("change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        phoneNumberTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTfActionPerformed(evt);
            }
        });

        jLabel8.setText("Phone Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(changeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumberTf)
                    .addComponent(pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lastName)
                    .addComponent(name)
                    .addComponent(userName)
                    .addComponent(balance)
                    .addComponent(debt)
                    .addComponent(lessonCredit))
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lessonCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(41, 41, 41)
                .addComponent(changeButton)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed

        try {
            int uid = studentInfo.getInt("UID");
            int balanceInt = Integer.parseInt(balance.getText());
            int debtInt = Integer.parseInt(debt.getText());
            int creditValue = Integer.parseInt(lessonCredit.getText());
            if (!name.getText().equals(nameDb)) {
                settingManager.setName(uid, name.getText());
                nameDb = name.getText();
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's name changed. New name :" + nameDb);
                }
            }
            if (!lastName.getText().equals(lastNameDb)) {
                settingManager.setLastName(uid, lastName.getText());
                lastNameDb = lastName.getText();
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's lastname changed. New lastname :" + lastNameDb);
                }
            }

            if (!userName.getText().equals(userNameDb)) {
                settingManager.setUsername(uid, userName.getText());
                userNameDb = userName.getText();
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's username changed. New username :" + userNameDb);
                }
            }
            if (!pass.getText().equals(passDb)) {
                settingManager.setPass(uid, pass.getText());
                passDb = pass.getText();
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's password changed. New password :" + passDb);
                }
            }
            if (balanceDb != balanceInt) {
                settingManager.setBalance(uid, balanceInt);
                balanceDb = balanceInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's balance changed. New balance :" + balanceDb);
                }
            }
            if (debtInt != debtDb) {
                settingManager.setDebt(uid, debtInt);
                debtDb = debtInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's debt changed. New debt :" + debtDb);
                }
            }
            if (creditValue != lessonCreditDb) {
                settingManager.setLessonCredit(uid, creditValue);
                lessonCreditDb = creditValue;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's lesson credit changed. New lesson credit :" + lessonCreditDb);
                }
            }
            if (!phoneNumberDb.equals(phoneNumberTf.getText())) {
                phoneNumberDb = phoneNumberTf.getText();
                settingManager.setPhoneNumber(uid, phoneNumberDb);
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered student's phone number changed . New phone number : " + phoneNumberDb);
                }
            }
            JOptionPane.showMessageDialog(null, "Successful.");
        } catch (SQLException | NumberFormatException | InputMismatchException | NotUniqueUsernameAndPassException | InvalidBalanceException | NotUniqueNameAndLastnameException | InvalidDebtException | InvalidLessonCreditException | InvalidUsernameLengthException | InvalidPassLengthException | IOException | NotUniquePhoneNumberException | InvalidPhoneNumberLengthException | InvalidPhoneCountryCodeException ex) {
            if (ex instanceof SQLException) {
                ex.printStackTrace();
            } else if (ex instanceof NumberFormatException || ex instanceof InputMismatchException) {
                JOptionPane.showMessageDialog(null, "Every process canceled. Invalid Input.");
            } else if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(null, "An error occured while writing to log file.");
            } else {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void debtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debtActionPerformed

    private void lessonCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonCreditActionPerformed

    private void phoneNumberTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStudentChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStudentChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStudentChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStudentChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField debt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField lessonCredit;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField phoneNumberTf;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
