/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kaan.schoolmanagementmaven.admin;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import com.kaan.schoolmanagementmaven.dataaccess.query.ILessonChangingQuery;
import com.kaan.schoolmanagementmaven.dataaccess.query.LessonChangingQuery;
import com.kaan.schoolmanagementmaven.exception.InvalidFinalRateException;
import com.kaan.schoolmanagementmaven.exception.InvalidLessonCreditException;
import com.kaan.schoolmanagementmaven.exception.InvalidLessonHourException;
import com.kaan.schoolmanagementmaven.exception.InvalidMidtermRateException;
import com.kaan.schoolmanagementmaven.exception.InvalidQuotaException;

/**
 *
 * @author kaan
 * 
 */
public class AdminLessonChangingPanel extends javax.swing.JFrame {

    private ResultSet lessonInfo;
    private ILessonChangingQuery lessonChanger;
    private String lessonName;
    private int lessonCredit;
    private int lessonHour;
    private int quota;
    private int uid;
    private int finalRate;
    private int midtermRate;

    /**
     * Creates new form AdminLessonChangingPanel
     *
     * @param lessonInfo
     */
    public AdminLessonChangingPanel(AdminLessonProcessPanel mainPanel, ResultSet lessonInfoSet) throws SQLException {
        initComponents();
        lessonInfo = lessonInfoSet;
        lessonName = lessonInfo.getString("lesson_name");
        lessonCredit = lessonInfo.getInt("lesson_credit");
        lessonHour = lessonInfo.getInt("lesson_hour");
        quota = lessonInfo.getInt("quota");
        uid = lessonInfo.getInt("lesson_UID");
        midtermRate = lessonInfo.getInt("average_midterm_rate");
        finalRate = lessonInfo.getInt("average_final_rate");
        name.setText(lessonName);
        credit.setText(Integer.toString(lessonCredit));
        hour.setText(Integer.toString(lessonHour));
        quotaTf.setText(Integer.toString(quota));
        midtermRateTf.setText(Integer.toString(midtermRate));
        finalRateTf.setText(Integer.toString(finalRate));
        lessonChanger = LessonChangingQuery.getInstance();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                mainPanel.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        hour = new javax.swing.JTextField();
        quotaTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lessonChangeButton = new javax.swing.JButton();
        midtermRateTf = new javax.swing.JTextField();
        finalRateTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lesson name ");

        jLabel2.setText("Lesson Credit");

        jLabel3.setText("Lesson Hour");

        jLabel4.setText("Quota");

        lessonChangeButton.setText("Change");
        lessonChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonChangeButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Final Rate");

        jLabel6.setText("Midterm Rate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(finalRateTf)
                            .addComponent(midtermRateTf)
                            .addComponent(quotaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lessonChangeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quotaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(midtermRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(finalRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(lessonChangeButton)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lessonChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonChangeButtonActionPerformed
        try {
            int creditInt = Integer.parseInt(credit.getText());
            int quotaInt = Integer.parseInt(quotaTf.getText());
            int hourInt = Integer.parseInt(hour.getText());
            int midtermRateInt = Integer.parseInt(midtermRateTf.getText());
            int finalRateInt = Integer.parseInt(finalRateTf.getText());
            if (!(lessonName.equals(name.getText()))) {
                lessonChanger.changeLessonName(name.getText(), uid);
                lessonName = name.getText();
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered lesson's name changed . New name : " + lessonName);
                }
            }
            if (lessonCredit != creditInt) {
                if (creditInt <= 0) {
                    throw new InvalidLessonCreditException();
                }
                lessonChanger.changeLessonCredit(creditInt, uid);
                lessonCredit = creditInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered lesson's credit changed . New credit : " + lessonCredit);
                }
            }
            if (quota != quotaInt) {
                if (quotaInt <= 0) {
                    throw new InvalidQuotaException();
                }
                lessonChanger.changeLessonQuota(quotaInt, uid);
                quota = quotaInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered lesson's quota changed . New quota : " + quota);
                }
            }
            if (lessonHour != hourInt) {
                if (hourInt <= 0) {
                    throw new InvalidLessonHourException();
                }
                lessonChanger.changeLessonHour(hourInt, uid);
                lessonHour = hourInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered lesson's hour changed . New hour : " + lessonHour);
                }
            }
            if (midtermRate != midtermRateInt) {
                if (midtermRateInt < 0 || midtermRateInt > 100) {
                    throw new InvalidMidtermRateException();
                }
                lessonChanger.changeLessonMidtermRate(midtermRateInt, uid);
                midtermRate = midtermRateInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered lesson's midterm rate changed . New midterm rate : " + midtermRate);
                }
            }

            if (finalRateInt != finalRate) {
                if (finalRateInt < 0 || finalRateInt > 100) {
                    throw new InvalidFinalRateException();
                }
                lessonChanger.changeLessonFinalRate(finalRateInt, uid);
                finalRate = finalRateInt;
                if (Admin.getLogManager() != null) {
                    Admin.getLogManager().saveMessage(uid + " UID numbered lesson's final rate changed . New final rate : " + finalRate);

                }
            }
            JOptionPane.showMessageDialog(null, "Successful");
        } catch (SQLException | NumberFormatException | InputMismatchException | InvalidQuotaException | InvalidLessonCreditException | InvalidLessonHourException | InvalidMidtermRateException | InvalidFinalRateException | IOException ex) {
            if (ex instanceof SQLException) {
                JOptionPane.showMessageDialog(null, "This lesson name is already in the database.");
            } else if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(null, "An error occured while writing log file.");
            } else if (ex instanceof NumberFormatException || ex instanceof InputMismatchException) {
                JOptionPane.showMessageDialog(null, "Invalid entry.");
            } else {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_lessonChangeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLessonChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLessonChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLessonChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLessonChangingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField credit;
    private javax.swing.JTextField finalRateTf;
    private javax.swing.JTextField hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lessonChangeButton;
    private javax.swing.JTextField midtermRateTf;
    private javax.swing.JTextField name;
    private javax.swing.JTextField quotaTf;
    // End of variables declaration//GEN-END:variables
}
