/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kaan.schoolmanagementmaven.admin;

import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.InputMismatchException;
import com.kaan.schoolmanagementmaven.dataaccess.query.ILessonAttendanceQuery;
import com.kaan.schoolmanagementmaven.dataaccess.query.ILessonFetchingQuery;
import com.kaan.schoolmanagementmaven.dataaccess.query.LessonAttendanceQuery;
import com.kaan.schoolmanagementmaven.dataaccess.query.LessonFetchingQuery;
import com.kaan.schoolmanagementmaven.exception.BoundAndOriginRangeSmallerThanRowNumberException;
import com.kaan.schoolmanagementmaven.exception.InvalidBoundAndOriginPairException;
import com.kaan.schoolmanagementmaven.exception.InvalidLessonCreditException;
import com.kaan.schoolmanagementmaven.exception.InvalidQuotaException;
import com.kaan.schoolmanagementmaven.exception.InvalidUIDException;
import com.kaan.schoolmanagementmaven.exception.NotUniqueLessonNameException;
import java.sql.ResultSet;
import com.kaan.schoolmanagementmaven.exception.InvalidFinalRateException;
import com.kaan.schoolmanagementmaven.exception.InvalidMidtermRateException;
import com.kaan.schoolmanagementmaven.exception.ReachedMaximumRowNumberException;

/**
 *
 * @author kaan
 *
 */
public class AdminLessonProcessPanel extends javax.swing.JFrame {

    private IAdminLessonManager lessonManager;
    private ILessonFetchingQuery lessonFetcher;
    private IAdminDefaultLessonProcessesManager defaultLessonProcessesManager;
    private ILessonAttendanceQuery lessonAttendanceQuery;

    /**
     * Creates new form AdminLessonAddingPanel
     */
    public AdminLessonProcessPanel(AdminPanel adminPanel) throws SQLException {
        initComponents();
        lessonManager = AdminLessonManager.getInstance();
        lessonList.removeAllItems();
        lessonFetcher = LessonFetchingQuery.getInstance();
        defaultLessonProcessesManager = AdminDefaultLessonProcessesManager.getInstance();
        lessonAttendanceQuery = LessonAttendanceQuery.getInstance();

        for (String currentLessonName : lessonFetcher.getAllLessonNames()) {
            lessonList.addItem(currentLessonName);
        }
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                adminPanel.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        lessonHour = new javax.swing.JTextField();
        lessonUIDOrigin = new javax.swing.JTextField();
        lessonUIDBound = new javax.swing.JTextField();
        quota = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        lessonList = new javax.swing.JComboBox<>();
        removeButton = new javax.swing.JButton();
        setOriginButton = new javax.swing.JButton();
        setBoundButton = new javax.swing.JButton();
        changeLessonButton = new javax.swing.JButton();
        finalRate = new javax.swing.JTextField();
        midtermRate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lesson Name");

        jLabel2.setText("Lesson Credit");

        jLabel3.setText("Lesson Hour");

        jLabel4.setText("Lesson UID Origin");

        jLabel5.setText("Lesson UID Bound");

        jLabel6.setText("Quota");

        lessonUIDBound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonUIDBoundActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        lessonList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        setOriginButton.setText("change");
        setOriginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOriginButtonActionPerformed(evt);
            }
        });

        setBoundButton.setText("change");
        setBoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBoundButtonActionPerformed(evt);
            }
        });

        changeLessonButton.setText("Change");
        changeLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLessonButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Midterm Rate");

        jLabel8.setText("Final Rate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(changeLessonButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeButton)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(setOriginButton)
                    .addComponent(setBoundButton))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lessonUIDBound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lessonList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lessonUIDOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(midtermRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lessonHour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(addButton)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lessonHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(midtermRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(finalRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setOriginButton)
                            .addComponent(lessonUIDOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lessonUIDBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(setBoundButton))
                        .addGap(41, 41, 41)
                        .addComponent(lessonList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeButton)
                            .addComponent(changeLessonButton))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(quota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lessonUIDBoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonUIDBoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonUIDBoundActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            String name = this.name.getText();
            int lessonCredit = Integer.parseInt(credit.getText());
            int lessonHour = Integer.parseInt(this.lessonHour.getText());
            int quota = Integer.parseInt(this.quota.getText());
            int midtermRate = Integer.parseInt(this.midtermRate.getText());
            int finalRate = Integer.parseInt(this.finalRate.getText());
            lessonManager.addLesson(name, lessonCredit, lessonHour, quota, midtermRate, finalRate);
            lessonList.addItem(name);
            lessonAttendanceQuery.addLessonAttendanceToDb(name);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Lesson added : " + name);

            }
        } catch (NumberFormatException | InputMismatchException | SQLException | NotUniqueLessonNameException | InvalidQuotaException | InvalidLessonCreditException | InvalidFinalRateException | InvalidMidtermRateException | IOException | ReachedMaximumRowNumberException ex) {
            if (ex instanceof NumberFormatException || ex instanceof InputMismatchException) {
                JOptionPane.showMessageDialog(null, "Invalid entry.");
            } else {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String name = (String) lessonList.getSelectedItem();
        int index = lessonList.getSelectedIndex();
        try {
            int uid = lessonFetcher.getLessonUIDByLessonName(name);
            lessonAttendanceQuery.removeLessonAttendanceFromDb(name);
            lessonManager.removeLesson(uid);
            lessonList.removeItemAt(index);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Lesson added : " + name);

            }
        } catch (SQLException | InvalidUIDException | IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void setOriginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOriginButtonActionPerformed
        String valueText = lessonUIDOrigin.getText();
        try {
            int value = Integer.parseInt(valueText);
            defaultLessonProcessesManager.setLessonUIDOrigin(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Lesson UID Origin value changed new value : " + value);

            }
        } catch (SQLException | NumberFormatException | InputMismatchException | InvalidBoundAndOriginPairException | IOException | BoundAndOriginRangeSmallerThanRowNumberException ex) {
            if (ex instanceof SQLException) {
                ex.printStackTrace();
            } else if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(null, "An error occured while writing to log file.");
            } else if (ex instanceof InvalidBoundAndOriginPairException) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Entry");
            }
        }
    }//GEN-LAST:event_setOriginButtonActionPerformed

    private void setBoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBoundButtonActionPerformed
        String valueText = lessonUIDBound.getText();
        try {
            int value = Integer.parseInt(valueText);
            defaultLessonProcessesManager.setLessonUIDBound(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Lesson UID Bound value changed new value : " + value);

            }
        } catch (SQLException | NumberFormatException | InputMismatchException | IOException | InvalidBoundAndOriginPairException | BoundAndOriginRangeSmallerThanRowNumberException ex) {
            if (ex instanceof SQLException) {
                ex.printStackTrace();
            } else if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(null, "An error occured while writing to log file.");
            } else if (ex instanceof InvalidBoundAndOriginPairException) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Entry");
            }
        }
    }//GEN-LAST:event_setBoundButtonActionPerformed

    private void changeLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLessonButtonActionPerformed
        String lessonName = (String) lessonList.getSelectedItem();
        try {
            int uid = lessonFetcher.getLessonUIDByLessonName(lessonName);
            this.setVisible(false);
            ResultSet resultSet = lessonFetcher.getLessonInfo(uid);
            resultSet.next();
            new AdminLessonChangingPanel(this, resultSet).setVisible(true);

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_changeLessonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLessonProcessPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLessonProcessPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLessonProcessPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLessonProcessPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton changeLessonButton;
    private javax.swing.JTextField credit;
    private javax.swing.JTextField finalRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lessonHour;
    private javax.swing.JComboBox<String> lessonList;
    private javax.swing.JTextField lessonUIDBound;
    private javax.swing.JTextField lessonUIDOrigin;
    private javax.swing.JTextField midtermRate;
    private javax.swing.JTextField name;
    private javax.swing.JTextField quota;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton setBoundButton;
    private javax.swing.JButton setOriginButton;
    // End of variables declaration//GEN-END:variables
}
