/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kaan.schoolmanagementmaven.admin;

import java.sql.SQLException;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import com.kaan.schoolmanagementmaven.dataaccess.query.IPersonFetchingQueries;
import com.kaan.schoolmanagementmaven.dataaccess.query.PersonFetchingQueries;
import java.sql.ResultSet;
import com.kaan.schoolmanagementmaven.dataaccess.query.IPersonLoginQueries;
import com.kaan.schoolmanagementmaven.dataaccess.query.PersonLoginQueries;
import com.kaan.schoolmanagementmaven.exception.InvalidUIDException;

/**
 *
 * @author kaan
 * 
 */
public class AdminPersonChangingMainPanel extends javax.swing.JFrame {

    private IAdminStudentInformationManager studentInfo;
    private IAdminTeacherInformationManager teacherInfo;
    private IPersonFetchingQueries personFetcher;
    private IPersonLoginQueries personLogin;

    /**
     * Creates new form AdminPersonChangingPanel
     *
     * @throws java.sql.SQLException
     */
    public AdminPersonChangingMainPanel(AdminPanel adminPanel) throws SQLException {
        initComponents();
        studentInfo = AdminPersonInformationManager.getInstanceForStudent();
        teacherInfo = AdminPersonInformationManager.getInstanceForTeacher();
        personFetcher = PersonFetchingQueries.getInstance();
        personLogin = PersonLoginQueries.getInstance();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                adminPanel.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        showAllStudentInfoButton = new javax.swing.JButton();
        teacherInfoButton = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Admin Student Changing Panel");

        uid.setText("Enter UID");

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        showAllStudentInfoButton.setText("Show All Student Info");
        showAllStudentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllStudentInfoButtonActionPerformed(evt);
            }
        });

        teacherInfoButton.setText("Show All Teacher Info");
        teacherInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(changeButton)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teacherInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showAllStudentInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeButton))
                .addGap(102, 102, 102)
                .addComponent(showAllStudentInfoButton)
                .addGap(75, 75, 75)
                .addComponent(teacherInfoButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAllStudentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllStudentInfoButtonActionPerformed
        try {
            String infoNormalStudent = studentInfo.getNormalStudentInfo();
            String infoWorkingStudent = studentInfo.getWorkingStudentInfo();
            JOptionPane.showMessageDialog(null, infoNormalStudent + "\n\n" + infoWorkingStudent);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_showAllStudentInfoButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        try {
            int UID = Integer.parseInt(uid.getText());
            ResultSet result1 = personFetcher.getNormalStudentInfo(UID);
            ResultSet copy1 = result1;
            if (copy1.next()) {
                String userName = personLogin.getNormalStudentUsernameByUID(UID);
                String pass = personLogin.getNormalStudentPassByUID(UID);
                this.setVisible(false);
                new AdminStudentChangingPanel(this, result1, userName, pass, "student_lesson_credit").setVisible(true);
                return;
            }
            ResultSet result2 = personFetcher.getWorkingStudentInfo(UID);
            ResultSet copy2 = result2;
            if (copy2.next()) {
                String userName = personLogin.getWorkingStudentUsernameByUID(UID);
                String pass = personLogin.getWorkingStudentPassByUID(UID);
                this.setVisible(false);
                new AdminStudentChangingPanel(this, result2, userName, pass, "student_lesson_credit").setVisible(true);
                return;
            }
            ResultSet result3 = personFetcher.getTeacherInfo(UID);
            ResultSet copy3 = result3;
            if (copy3.next()) {
                String userName = personLogin.getTeacherUsernameByUID(UID);
                String pass = personLogin.getTeacherPassByUID(UID);
                this.setVisible(false);
                new AdminTeacherChangingPanel(this, result3, userName, pass).setVisible(true);
                return;
            }
            throw new InvalidUIDException();
        } catch (NumberFormatException | InputMismatchException | SQLException | InvalidUIDException ex) {
            if (ex instanceof SQLException) {
                ex.printStackTrace();
            } else if (ex instanceof InvalidUIDException) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Number format.");
            }
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void teacherInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherInfoButtonActionPerformed
        try {
            String result = teacherInfo.getTeacherInfo();
            JOptionPane.showMessageDialog(null, result);
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_teacherInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPersonChangingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPersonChangingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPersonChangingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPersonChangingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JButton showAllStudentInfoButton;
    private javax.swing.JButton teacherInfoButton;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
