/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kaan.schoolmanagementmaven.admin;

import com.kaan.schoolmanagementmaven.exception.BoundAndOriginRangeSmallerThanRowNumberException;
import com.kaan.schoolmanagementmaven.exception.IntersectingUIDRangeException;
import com.kaan.schoolmanagementmaven.exception.InvalidBalanceException;
import java.io.IOException;
import javax.swing.JOptionPane;
import com.kaan.schoolmanagementmaven.exception.InvalidLessonCreditException;
import com.kaan.schoolmanagementmaven.exception.InvalidMaxDebtCreditException;
import com.kaan.schoolmanagementmaven.person.Student;
import java.sql.SQLException;
import java.util.InputMismatchException;
import java.util.Map;
import java.util.Map.Entry;
import com.kaan.schoolmanagementmaven.exception.InvalidBoundAndOriginPairException;
import com.kaan.schoolmanagementmaven.exception.InvalidCostForPerHourException;
import com.kaan.schoolmanagementmaven.exception.InvalidDebtException;
import com.kaan.schoolmanagementmaven.exception.InvalidPhoneCountryCodeException;
import com.kaan.schoolmanagementmaven.exception.InvalidPhoneNumberLengthException;
import com.kaan.schoolmanagementmaven.exception.NotUniqueNameAndLastnameException;
import com.kaan.schoolmanagementmaven.exception.NotUniquePhoneNumberException;
import com.kaan.schoolmanagementmaven.exception.ReachedMaximumRowNumberException;

/**
 *
 * @author kaan
 *
 */
public class AdminStudentAddingPanel extends javax.swing.JFrame {

    private AdminPanel adminPanel;
    private Admin admin;

    /**
     * Creates new form StudentProcessesPanel
     *
     * @param adminPanel
     * @param admin
     */
    public AdminStudentAddingPanel(AdminPanel adminPanel, Admin admin) {
        initComponents();
        this.adminPanel = adminPanel;
        this.admin = admin;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                adminPanel.setVisible(true); // İkinci JFrame kapatıldığında ilk JFrame'i görünür yap
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        defaultLessonCreditTextField = new javax.swing.JTextField();
        defaultLessonCreditButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        maxDebtCreditButton = new javax.swing.JButton();
        maxDebtCreditTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        normalStudentName = new javax.swing.JTextField();
        normalStudentLastName = new javax.swing.JTextField();
        normalStudentAddingButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        workingStudentName = new javax.swing.JTextField();
        workingStudentLastName = new javax.swing.JTextField();
        workingStudentAddingButton = new javax.swing.JButton();
        normalStudentUIDOriginTextField = new javax.swing.JTextField();
        normalStudentUIDOriginButton = new javax.swing.JButton();
        normalStudentUIDBoundButton = new javax.swing.JButton();
        workingStudentUIDOriginButton = new javax.swing.JButton();
        workingStudentUIDBoundButton = new javax.swing.JButton();
        normalStudentUIDBoundTextField = new javax.swing.JTextField();
        workingStudentUIDOriginTextField = new javax.swing.JTextField();
        workingStudentUIDBoundTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        costForPerHourButton = new javax.swing.JButton();
        costForPerHour = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        normalStudentPhoneNumber = new javax.swing.JTextField();
        workingStudentPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        defaultBalanceTf = new javax.swing.JTextField();
        defaultDebtTf = new javax.swing.JTextField();
        defaultBalanceChangeButton = new javax.swing.JButton();
        defaultDebtChangeButton = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        defaultLessonCreditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultLessonCreditTextFieldActionPerformed(evt);
            }
        });

        defaultLessonCreditButton.setText("change");
        defaultLessonCreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultLessonCreditButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Default Lesson Credit");

        maxDebtCreditButton.setText("change");
        maxDebtCreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxDebtCreditButtonActionPerformed(evt);
            }
        });

        maxDebtCreditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxDebtCreditTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Max Debt Credit");

        jLabel3.setText("Admin Student Adding Panel");

        normalStudentName.setText("Name");

        normalStudentLastName.setText("Lastname");
        normalStudentLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStudentLastNameActionPerformed(evt);
            }
        });

        normalStudentAddingButton.setText("Add");
        normalStudentAddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStudentAddingButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Add Normal Student");

        jLabel5.setText("Add Working Student");

        workingStudentName.setText("Name");

        workingStudentLastName.setText("Lastname");

        workingStudentAddingButton.setText("Add");
        workingStudentAddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingStudentAddingButtonActionPerformed(evt);
            }
        });

        normalStudentUIDOriginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStudentUIDOriginTextFieldActionPerformed(evt);
            }
        });

        normalStudentUIDOriginButton.setText("change");
        normalStudentUIDOriginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStudentUIDOriginButtonActionPerformed(evt);
            }
        });

        normalStudentUIDBoundButton.setText("change");
        normalStudentUIDBoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStudentUIDBoundButtonActionPerformed(evt);
            }
        });

        workingStudentUIDOriginButton.setText("change");
        workingStudentUIDOriginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingStudentUIDOriginButtonActionPerformed(evt);
            }
        });

        workingStudentUIDBoundButton.setText("change");
        workingStudentUIDBoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingStudentUIDBoundButtonActionPerformed(evt);
            }
        });

        workingStudentUIDOriginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingStudentUIDOriginTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Normal Student UID Origin");

        jLabel7.setText("Normal Student UID Bound");

        jLabel8.setText("Working Student UID Origin");

        jLabel9.setText("Working Student UID Bound");

        costForPerHourButton.setText("change");
        costForPerHourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costForPerHourButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Cost For Per Hour Of Working Students");

        normalStudentPhoneNumber.setText("Phone Number");

        workingStudentPhoneNumber.setText("Phone Number");

        jLabel11.setText("Default Balance");

        jLabel12.setText("Default Debt");

        defaultBalanceChangeButton.setText("change");
        defaultBalanceChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultBalanceChangeButtonActionPerformed(evt);
            }
        });

        defaultDebtChangeButton.setText("   change");
        defaultDebtChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultDebtChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(258, 258, 258)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defaultLessonCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxDebtCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(379, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(163, 163, 163)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(workingStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(normalStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(normalStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(workingStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(70, 70, 70)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(normalStudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(workingStudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(62, 62, 62))
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(144, 144, 144)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(normalStudentUIDOriginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(normalStudentUIDBoundTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(workingStudentUIDOriginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(workingStudentUIDBoundTextField)
                                        .addComponent(costForPerHour, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(defaultBalanceTf)
                                        .addComponent(defaultDebtTf))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(598, 598, 598)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(normalStudentUIDBoundButton)
                            .addComponent(maxDebtCreditButton)
                            .addComponent(defaultLessonCreditButton)
                            .addComponent(costForPerHourButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(normalStudentAddingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(workingStudentAddingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(workingStudentUIDBoundButton)
                            .addComponent(workingStudentUIDOriginButton)
                            .addComponent(normalStudentUIDOriginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defaultBalanceChangeButton)
                            .addComponent(defaultDebtChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(defaultLessonCreditButton)
                            .addComponent(defaultLessonCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(maxDebtCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxDebtCreditButton))
                        .addGap(30, 30, 30)
                        .addComponent(costForPerHourButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(costForPerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(defaultBalanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(defaultBalanceChangeButton)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(defaultDebtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultDebtChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(normalStudentUIDOriginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(normalStudentUIDOriginButton))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(normalStudentUIDBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalStudentUIDBoundButton))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workingStudentUIDOriginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(workingStudentUIDOriginButton))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(workingStudentUIDBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(workingStudentUIDBoundButton)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(normalStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalStudentAddingButton)
                    .addComponent(normalStudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workingStudentAddingButton)
                    .addComponent(workingStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workingStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(workingStudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultLessonCreditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultLessonCreditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultLessonCreditTextFieldActionPerformed

    private void defaultLessonCreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultLessonCreditButtonActionPerformed
        String valueString = defaultLessonCreditTextField.getText();
        int value = 0;
        try {
            value = Integer.parseInt(valueString);
            Student.setDefaultLessonCredit(value);
            admin.getAdminDefaultStudentProcessesObject().setDefaultLessonCredit(value);
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Student's default lesson credit value changed . New value : " + value);

            }
            JOptionPane.showMessageDialog(null, "New lesson credit : " + value);
        } catch (NumberFormatException | InvalidLessonCreditException | SQLException | IOException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_defaultLessonCreditButtonActionPerformed

    private void maxDebtCreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxDebtCreditButtonActionPerformed
        String valueString = maxDebtCreditTextField.getText();
        int value = 0;
        try {
            value = Integer.parseInt(valueString);
            Student.setDefaultMaxDebtCredit(value);
            admin.getAdminDefaultStudentProcessesObject().setDefaultMaxDebtCredit(value);
            JOptionPane.showMessageDialog(null, "New debt credit : " + value);
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Student's default max debt credit value changed . New value : " + value);
            }
        } catch (NumberFormatException | InvalidMaxDebtCreditException | SQLException | IOException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_maxDebtCreditButtonActionPerformed

    private void maxDebtCreditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxDebtCreditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxDebtCreditTextFieldActionPerformed

    private void normalStudentLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStudentLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalStudentLastNameActionPerformed

    private void normalStudentAddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStudentAddingButtonActionPerformed
        String name = normalStudentName.getText();
        String lastName = normalStudentLastName.getText();
        String phoneNumber = normalStudentPhoneNumber.getText();
        try {
            Map<String, String> userNameAndPass = admin.getAdminAddingManager().addNormalStudent(name, lastName, phoneNumber);
            String userName = null, password = null;
            for (Entry<String, String> entry : userNameAndPass.entrySet()) {
                userName = entry.getKey();
                password = entry.getValue();
            }
            JOptionPane.showMessageDialog(null, "Successful.\nUsername : " + userName + "\nPassword : " + password);
            /*
            Admin.getOptionalLogManager().ifPresent(logManager -> {
                try {
                    logManager.getBufferedWriter().write("Normal student added : " + name + "  " + lastName);
                    logManager.getBufferedWriter().close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "An error occurred while writing to the log file.");
                }
            });
             */
 /*
            if (Admin.getOptionalLogManager().isPresent()) {
                Admin.getLogManager().saveMessage(userName);        // Optionalin icersinde nesne olmasina ragmen isPresent() false donuyor          
            }
             */
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Normal student added : " + name + "  " + lastName);
            }
        } catch (SQLException | IOException | IntersectingUIDRangeException | NotUniqueNameAndLastnameException | InvalidPhoneCountryCodeException | InvalidPhoneNumberLengthException | NotUniquePhoneNumberException | ReachedMaximumRowNumberException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_normalStudentAddingButtonActionPerformed

    private void workingStudentAddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingStudentAddingButtonActionPerformed
        String name = workingStudentName.getText();
        String lastName = workingStudentLastName.getText();
        String phoneNumber = workingStudentPhoneNumber.getText();
        try {
            Map<String, String> userNameAndPass = admin.getAdminAddingManager().addWorkingStudent(name, lastName, phoneNumber);
            String userName = null, password = null;
            for (Entry<String, String> entry : userNameAndPass.entrySet()) {
                userName = entry.getKey();
                password = entry.getValue();
            }
            JOptionPane.showMessageDialog(null, "Successful.\nUsername : " + userName + "\nPassword : " + password);
            /*
            Admin.getOptionalLogManager().ifPresent(logManager -> {
                try {
                    logManager.saveMessage("Working student added : " + name + "  " + lastName);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "An error occurred while writing to the log file.");
                }
            });
             */
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Working student added : " + name + "  " + lastName);
            }
        } catch (IntersectingUIDRangeException | SQLException | NotUniqueNameAndLastnameException | InvalidPhoneCountryCodeException | InvalidPhoneNumberLengthException | NotUniquePhoneNumberException | IOException | ReachedMaximumRowNumberException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_workingStudentAddingButtonActionPerformed

    private void normalStudentUIDOriginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStudentUIDOriginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalStudentUIDOriginTextFieldActionPerformed

    private void normalStudentUIDOriginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStudentUIDOriginButtonActionPerformed
        String valueText = normalStudentUIDOriginTextField.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setDefaultNormalStudentUIDOrigin(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Normal student UID Origin value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | SQLException | InvalidBoundAndOriginPairException | IOException | BoundAndOriginRangeSmallerThanRowNumberException ex) {
            showErrorMessage(ex);
        }

    }//GEN-LAST:event_normalStudentUIDOriginButtonActionPerformed

    private void normalStudentUIDBoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStudentUIDBoundButtonActionPerformed
        String valueText = normalStudentUIDBoundTextField.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setDefaultNormalStudentUIDBound(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Normal student UID Bound value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | SQLException | InvalidBoundAndOriginPairException | IOException | BoundAndOriginRangeSmallerThanRowNumberException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_normalStudentUIDBoundButtonActionPerformed

    private void workingStudentUIDOriginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingStudentUIDOriginButtonActionPerformed
        String valueText = workingStudentUIDOriginTextField.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setDefaultWorkingStudentUIDOrigin(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Working student UID Origin value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | SQLException | InvalidBoundAndOriginPairException | IOException | BoundAndOriginRangeSmallerThanRowNumberException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_workingStudentUIDOriginButtonActionPerformed

    private void workingStudentUIDOriginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingStudentUIDOriginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workingStudentUIDOriginTextFieldActionPerformed

    private void workingStudentUIDBoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingStudentUIDBoundButtonActionPerformed
        String valueText = workingStudentUIDBoundTextField.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setDefaultWorkingStudentUIDBound(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Working student UID Bound value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | SQLException | InvalidBoundAndOriginPairException | IOException | BoundAndOriginRangeSmallerThanRowNumberException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_workingStudentUIDBoundButtonActionPerformed

    private void costForPerHourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costForPerHourButtonActionPerformed
        String valueText = costForPerHour.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setCostForPerHourForWorkingStudents(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Working student's cost for per hour value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | InvalidCostForPerHourException | SQLException | IOException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_costForPerHourButtonActionPerformed

    private void defaultBalanceChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultBalanceChangeButtonActionPerformed
        String valueText = defaultBalanceTf.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setDefaultBalance(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Default balance value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | InvalidBalanceException | SQLException | IOException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_defaultBalanceChangeButtonActionPerformed

    private void defaultDebtChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultDebtChangeButtonActionPerformed
        String valueText = defaultDebtTf.getText();
        try {
            int value = Integer.parseInt(valueText);
            admin.getAdminDefaultStudentProcessesObject().setDefaultDebt(value);
            JOptionPane.showMessageDialog(null, "Successful.");
            if (Admin.getLogManager() != null) {
                Admin.getLogManager().saveMessage("Default debt value changed . New value : " + value);
            }
        } catch (NumberFormatException | InputMismatchException | InvalidDebtException | SQLException | IOException ex) {
            showErrorMessage(ex);
        }
    }//GEN-LAST:event_defaultDebtChangeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStudentAddingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStudentAddingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStudentAddingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStudentAddingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }

        });
    }

    private void showErrorMessage(Exception ex) {
        if (ex instanceof NumberFormatException || ex instanceof InputMismatchException) {
            JOptionPane.showMessageDialog(null, "Invalid entry.");
        } else {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costForPerHour;
    private javax.swing.JButton costForPerHourButton;
    private javax.swing.JButton defaultBalanceChangeButton;
    private javax.swing.JTextField defaultBalanceTf;
    private javax.swing.JTextField defaultDebtChangeButton;
    private javax.swing.JTextField defaultDebtTf;
    private javax.swing.JButton defaultLessonCreditButton;
    private javax.swing.JTextField defaultLessonCreditTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maxDebtCreditButton;
    private javax.swing.JTextField maxDebtCreditTextField;
    private javax.swing.JButton normalStudentAddingButton;
    private javax.swing.JTextField normalStudentLastName;
    private javax.swing.JTextField normalStudentName;
    private javax.swing.JTextField normalStudentPhoneNumber;
    private javax.swing.JButton normalStudentUIDBoundButton;
    private javax.swing.JTextField normalStudentUIDBoundTextField;
    private javax.swing.JButton normalStudentUIDOriginButton;
    private javax.swing.JTextField normalStudentUIDOriginTextField;
    private javax.swing.JButton workingStudentAddingButton;
    private javax.swing.JTextField workingStudentLastName;
    private javax.swing.JTextField workingStudentName;
    private javax.swing.JTextField workingStudentPhoneNumber;
    private javax.swing.JButton workingStudentUIDBoundButton;
    private javax.swing.JTextField workingStudentUIDBoundTextField;
    private javax.swing.JButton workingStudentUIDOriginButton;
    private javax.swing.JTextField workingStudentUIDOriginTextField;
    // End of variables declaration//GEN-END:variables
}
